"use client";

/**
 * PDF report download. The four-page report is generated by the existing
 * Python report generator; the browser only fetches the bytes.
 */

import { Download, Loader2 } from "lucide-react";
import { useState } from "react";

import { api, errorMessage } from "@/lib/api";
import { ErrorState } from "./ui/States";

export default function ReportDownload({
  station,
  className = "",
  label = "Download escalation report (PDF)",
  variant = "primary",
  onDownloaded,
}: {
  station: string;
  className?: string;
  label?: string;
  variant?: "primary" | "ghost";
  onDownloaded?: () => void;
}) {
  const [downloading, setDownloading] = useState(false);
  const [error, setError] = useState<Error | null>(null);

  async function handleDownload() {
    setDownloading(true);
    setError(null);
    try {
      await api.downloadReport(station);
      onDownloaded?.();
    } catch (err) {
      setError(err instanceof Error ? err : new Error(errorMessage(err)));
    } finally {
      setDownloading(false);
    }
  }

  const styles =
    variant === "primary"
      ? "border-aree-accent/60 text-aree-accent hover:bg-aree-accent/10 hover:border-aree-accent bg-aree-surface-1 shadow-[var(--aree-shadow-sm)]"
      : "border-aree-border text-aree-muted hover:border-aree-border-strong hover:text-aree-body bg-transparent";

  return (
    <div className={className}>
      <button
        type="button"
        onClick={handleDownload}
        disabled={downloading}
        className={`flex items-center gap-2 rounded-[var(--aree-radius-md)] border px-4 py-2.5 text-[12.5px] font-semibold transition-all disabled:opacity-60 ${styles}`}
      >
        {downloading ? (
          <Loader2 className="h-4 w-4 animate-spin" aria-hidden />
        ) : (
          <Download className="h-4 w-4" aria-hidden />
        )}
        {downloading ? "Generating report…" : label}
      </button>

      {error ? (
        <div className="mt-3">
          <ErrorState error={error} onRetry={handleDownload} compact />
        </div>
      ) : null}
    </div>
  );
}
