"use client";

/**
 * PDF report download. The four-page report is generated by the existing Python
 * report generator; the browser only fetches the bytes.
 *
 * WHAT THIS COMPONENT IS RESPONSIBLE FOR BEYOND THE FETCH
 *   Three things, all of which used to be the operator's problem:
 *
 *   THE DEADLINE. Generation is a single synchronous request with no progress feed,
 *   so without a deadline a stuck generator is indistinguishable from a slow one and
 *   the button spins until the tab is closed.
 *
 *   THE STALE GATE. A brief built from a twenty-hour-old reading is still a valid
 *   document and is sometimes exactly what is wanted — but it must not be produced by
 *   accident. The operator is told the age and asked once.
 *
 *   THE FAILURE. Every way this can fail maps to a different thing the authority
 *   should do next; see lib/reportErrors.
 */

import { AlertTriangle, Check, Download, Loader2, Printer } from "lucide-react";
import { useState } from "react";

import ReportError from "@/components/reports/ReportError";
import ReportProgress, {
  useGenerationProgress,
} from "@/components/reports/ReportProgress";
import { api, errorMessage, withTimeout } from "@/lib/api";
import { istDateTime } from "@/lib/clock";
import { formatDuration } from "@/lib/duration";
import { stationLabel } from "@/lib/station";
import type { FreshnessStatus } from "@/types";

/**
 * How long generation gets before it is abandoned.
 *
 * Far longer than the ten seconds a read gets elsewhere, and deliberately: this is
 * not a read. The engine collects, validates, analyses, evaluates and renders a
 * four-page document, and a few seconds of that is normal. Thirty is long enough
 * that a healthy generator is never cut off and short enough that a wedged one is
 * reported while the operator is still at the screen.
 */
const GENERATION_TIMEOUT_MS = 30000;

export default function ReportDownload({
  station,
  className = "",
  label = "Download escalation report (PDF)",
  variant = "primary",
  onDownloaded,
  showPrint,
  freshnessStatus,
  staleSeconds,
}: {
  station: string;
  className?: string;
  label?: string;
  variant?: "primary" | "ghost";
  onDownloaded?: () => void;
  /**
   * Offer "Print / Save as PDF" beside the download.
   *
   * Defaults to the primary variant only. The ghost variant is used inside dense
   * rows — a station list, a history table — where the row is not the thing being
   * printed and a second control per row would be noise. Pass it explicitly to
   * override either way.
   */
  showPrint?: boolean;
  /**
   * The engine's freshness classification for this station, where the caller
   * already has it.
   *
   * Optional on purpose. This component is rendered in places that hold only a
   * station key, and it must not grow a fetch of its own to find out — the caller
   * that already polled the station passes what it knows, and the gate below simply
   * does not arm where nobody knows.
   */
  freshnessStatus?: FreshnessStatus | null;
  /** Age of the reading in seconds, from the same payload as `freshnessStatus`. */
  staleSeconds?: number | null;
}) {
  const [downloading, setDownloading] = useState(false);
  const [error, setError] = useState<Error | null>(null);
  /* Recorded beside the error, never derived at render time: a timestamp computed
     while painting would tick forward on every re-render and claim the failure
     happened just now, which is the one thing it is there to disprove. */
  const [errorAt, setErrorAt] = useState<string | null>(null);
  const [succeededAt, setSucceededAt] = useState<string | null>(null);
  /* Set when the operator has been shown the age of the data and has not yet
     answered. Cleared either way, so the question is asked once per attempt and
     never becomes a click-through. */
  const [confirmingStale, setConfirmingStale] = useState(false);

  const progress = useGenerationProgress();

  const stale = freshnessStatus === "stale";
  const age = formatDuration(staleSeconds);

  async function runDownload() {
    setDownloading(true);
    setError(null);
    setErrorAt(null);
    setSucceededAt(null);
    setConfirmingStale(false);
    /* Started here, in the click handler, and NOT from an effect: the sequence is a
       consequence of the operator pressing the button, not of this component
       rendering. The request goes out on the same tick — the stages run beside it,
       they do not gate it. */
    progress.start();
    try {
      await withTimeout(GENERATION_TIMEOUT_MS, (signal) =>
        api.downloadReport(station, signal),
      );
      progress.succeed();
      setSucceededAt(new Date().toISOString());
      onDownloaded?.();
    } catch (err) {
      progress.fail();
      setError(err instanceof Error ? err : new Error(errorMessage(err)));
      setErrorAt(new Date().toISOString());
    } finally {
      setDownloading(false);
    }
  }

  function handleDownload() {
    // Asked once, before the request, and only when the engine has actually
    // classified the reading as stale. Aging data is not gated: it is older than
    // expected but still inside the window for an hourly feed, and a prompt on every
    // second station is a prompt nobody reads.
    if (stale && !confirmingStale) {
      setConfirmingStale(true);
      setError(null);
      setErrorAt(null);
      return;
    }
    void runDownload();
  }

  const styles =
    variant === "primary"
      ? "border-aree-accent/60 text-aree-accent hover:bg-aree-accent/10 hover:border-aree-accent bg-aree-surface-1 shadow-[var(--aree-shadow-sm)]"
      : "border-aree-border text-aree-muted hover:border-aree-border-strong hover:text-aree-body bg-transparent";

  /* Secondary to the download in weight, because it produces a different artefact.
     The PDF is the engine's four-page brief, generated by the Python report
     generator and identical for everyone who asks for it. This prints THE PAGE —
     what the operator is actually looking at, including the freshness and replay
     context around it — which is the right output when the question is "show me
     what you were looking at when you made the call". */
  const printable = showPrint ?? variant === "primary";

  /* The stage list and the banners belong to the deliberate, one-at-a-time generation
     on the report centre. The ghost variant is used inside dense rows — a station
     catalogue, a history table — where five chips per row would bury the rows
     themselves; there the button's own spinner remains the whole indicator. */
  const verbose = variant === "primary";

  return (
    <div className={className}>
      <div className="flex flex-wrap items-center gap-2">
        <button
          type="button"
          onClick={handleDownload}
          disabled={downloading}
          className={`flex items-center gap-2 rounded-[var(--aree-radius-md)] border px-4 py-2.5 text-[12.5px] font-semibold transition-all disabled:opacity-60 ${styles}`}
        >
          {downloading ? (
            <Loader2 className="h-4 w-4 animate-spin" aria-hidden />
          ) : (
            <Download className="h-4 w-4" aria-hidden />
          )}
          {downloading ? "Generating report…" : label}
        </button>

        {printable ? (
          <button
            type="button"
            onClick={() => window.print()}
            className="flex items-center gap-2 rounded-[var(--aree-radius-md)] border border-aree-border bg-transparent px-4 py-2.5 text-[12.5px] font-semibold text-aree-muted transition-all hover:border-aree-border-strong hover:text-aree-body"
            aria-label="Print this page, or save it as a PDF"
          >
            <Printer className="h-4 w-4" aria-hidden />
            Print / Save as PDF
          </button>
        ) : null}
      </div>

      {/* The stale gate. It states the age, states what the document will say about
          it, and asks — it does not refuse. Generating a brief from old data is a
          legitimate act; doing it without noticing is the failure being prevented. */}
      {confirmingStale ? (
        <div
          role="alertdialog"
          aria-label="Confirm generating a report from stale data"
          className="mt-3 rounded-[var(--aree-radius-md)] px-4 py-3.5"
          style={{
            border: "1px solid color-mix(in srgb, var(--aree-orange) 50%, transparent)",
            background: "color-mix(in srgb, var(--aree-orange) 7%, transparent)",
          }}
        >
          <div className="flex items-start gap-3">
            <AlertTriangle
              className="mt-0.5 h-4 w-4 shrink-0"
              style={{ color: "var(--aree-orange)" }}
              aria-hidden
            />
            <div className="min-w-0 flex-1">
              <p className="text-[12.5px] leading-relaxed text-aree-body">
                The most recent data for {stationLabel(station)} is{" "}
                <span className="aree-num font-bold" style={{ color: "var(--aree-orange)" }}>
                  {age ?? "over the staleness threshold"}
                </span>{" "}
                old. The report will note this. Continue anyway?
              </p>
              <div className="mt-3 flex flex-wrap gap-2">
                <button
                  type="button"
                  onClick={() => void runDownload()}
                  className="rounded-[var(--aree-radius-sm)] px-3.5 py-1.5 text-[12px] font-bold text-aree-on-solid transition"
                  style={{ background: "var(--aree-orange)" }}
                >
                  Confirm and generate
                </button>
                <button
                  type="button"
                  onClick={() => setConfirmingStale(false)}
                  className="rounded-[var(--aree-radius-sm)] border border-aree-border px-3.5 py-1.5 text-[12px] font-semibold text-aree-body transition hover:border-aree-border-strong"
                >
                  Cancel
                </button>
              </div>
            </div>
          </div>
        </div>
      ) : null}

      {verbose ? (
        <div className="mt-3">
          <ReportProgress progress={progress} stationLabel={stationLabel(station)} />
        </div>
      ) : null}

      {/* Success is stated as plainly as failure, and carries the same timestamp.
          A browser download can land silently in a folder the operator never looks
          at; this is the confirmation that it happened and when. */}
      {verbose && succeededAt && !error ? (
        <div
          role="status"
          className="mt-3 flex items-start gap-2.5 rounded-[var(--aree-radius-md)] px-4 py-3"
          style={{
            border: "1px solid color-mix(in srgb, var(--aree-green) 45%, transparent)",
            background: "color-mix(in srgb, var(--aree-green) 7%, transparent)",
          }}
        >
          <Check
            className="mt-0.5 h-4 w-4 shrink-0"
            style={{ color: "var(--aree-green)" }}
            aria-hidden
          />
          <div className="min-w-0">
            <div
              className="text-[12.5px] font-bold"
              style={{ color: "var(--aree-green)" }}
            >
              Report downloaded
            </div>
            <div className="aree-num mt-0.5 text-[11px] text-aree-muted">
              {stationLabel(station)} · {istDateTime(succeededAt)}
            </div>
          </div>
        </div>
      ) : null}

      {error ? (
        <div className="mt-3">
          <ReportError error={error} occurredAt={errorAt} onRetry={() => void runDownload()} />
        </div>
      ) : null}
    </div>
  );
}
