"""PDF escalation reports generated by the existing report_generator."""

import re
from urllib.parse import quote

from fastapi import APIRouter, HTTPException, Path, Response

from .. import engine
from ..deps import require_state
from ..schemas import ReportMetaResponse
from ..serialization import engine_mode

router = APIRouter(tags=["reports"])


def _filename(station: str) -> str:
    safe = re.sub(r"[^A-Za-z0-9_.-]+", "_", station).strip("_")[:60] or "station"
    return f"escalation_report_{safe}.pdf"


@router.get("/reports/{station:path}/pdf",
            summary="Download the 4-page municipal escalation report",
            response_class=Response,
            responses={200: {"content": {"application/pdf": {}}}})
def report_pdf(station: str = Path(...)) -> Response:
    state, _ = require_state(station)

    try:
        pdf_bytes = engine.generate_report(station, state)
    except Exception as exc:  # noqa: BLE001
        raise HTTPException(
            status_code=500,
            detail={
                "error": "report_generation_failed",
                "detail": f"{type(exc).__name__}: {exc}",
            },
        ) from exc

    name = _filename(station)
    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={
            "Content-Disposition": (
                f"attachment; filename=\"{name}\"; filename*=UTF-8''{quote(name)}"
            ),
            "Content-Length": str(len(pdf_bytes)),
        },
    )


@router.get("/reports/{station:path}", response_model=ReportMetaResponse,
            summary="Report availability and download link")
def report_meta(station: str = Path(...)) -> ReportMetaResponse:
    state, _ = require_state(station)
    c = engine.config()

    return ReportMetaResponse(
        station=station,
        available=True,
        generated_for=station,
        engine_mode=engine_mode(
            state.get("aqi"), state.get("consecutive_windows"),
            c.HIGH_AQI_THRESHOLD, c.PERSISTENCE_THRESHOLD,
        ),
        aqi=state.get("aqi"),
        grap_stage=state.get("grap_stage"),
        pdf_url=f"/api/reports/{quote(station, safe='')}/pdf",
        filename=_filename(station),
    )
